version: '3.6'

services:
    ollama: 
      image: ollama/ollama:latest
      volumes:
        - /ollama/models:/ollama/models
      environment:
        - OLLAMA_MODELS=/ollama/models
    
    chroma:
      image: chromadb/chroma:0.5.1.dev111
      volumes:
        - index_data:/chroma/.chroma/index
      ports:
        - 8000:8000
      networks:
        - net
    
    ui:
      build: ./app
      ports:
        - 8080:8080
      volumes:
        - ./app:/app
      networks:
        - net
      depends_on:
        - ollama
        - chroma
      environment:
        - MODEL=phi3
        # Embedding model used for document ingestion and retrieval
        - EMBEDDINGS_MODEL_NAME=sentence-transformers/all-mpnet-base-v2
        - TARGET_SOURCE_CHUNKS=5
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/_stcore/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    api:
      build: ./app
      ports:
        - 8081:8081
      volumes:
        - ./app:/app
      networks:
        - net
      depends_on:
        - ollama
        - chroma
      environment:
        - MODEL=phi3
        # Embedding model used for document ingestion and retrieval
        - EMBEDDINGS_MODEL_NAME=sentence-transformers/all-mpnet-base-v2
        - TARGET_SOURCE_CHUNKS=5
        - ANCLORA_API_TOKENS=${ANCLORA_API_TOKENS:-}
        - ANCLORA_API_TOKEN=${ANCLORA_API_TOKEN:-}
        - ANCLORA_JWT_SECRET=${ANCLORA_JWT_SECRET:-}
        - ANCLORA_JWT_ALGORITHMS=${ANCLORA_JWT_ALGORITHMS:-HS256}
        - ANCLORA_JWT_AUDIENCE=${ANCLORA_JWT_AUDIENCE:-}
        - ANCLORA_JWT_ISSUER=${ANCLORA_JWT_ISSUER:-}
      command: ["python", "-m", "uvicorn", "api_endpoints:app", "--host", "0.0.0.0", "--port", "8081"]
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

volumes:
  index_data:

networks:
  net:
