version: '3.6'

services:
    ollama: 
      image: ollama/ollama:latest
      volumes:
        - /ollama/models:/home/models
      environment:
        - OLLAMA_MODELS=/home/models
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
    
    chroma:
      image: chromadb/chroma:0.5.1.dev111
      volumes:
        - index_data:/chroma/.chroma/index
      ports:
        - 8000:8000
      networks:
        - net
    
    nvidia:
      image: nvidia/cuda:12.3.1-base-ubuntu20.04
      command: nvidia-smi
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    
    ui:
      build: ./app
      ports:
        - 8080:8080
      volumes:
        - ./app:/app
      networks:
        - net
      depends_on:
        - nvidia
        - ollama
        - chroma
      environment:
        - MODEL=llama3
        # Embedding model used for document ingestion and retrieval
        - EMBEDDINGS_MODEL_NAME=sentence-transformers/all-mpnet-base-v2
        - TARGET_SOURCE_CHUNKS=5
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/_stcore/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    api:
      build: ./app
      ports:
        - 8081:8081
      volumes:
        - ./app:/app
      networks:
        - net
      depends_on:
        - nvidia
        - ollama
        - chroma
      environment:
        - MODEL=llama3
        # Embedding model used for document ingestion and retrieval
        - EMBEDDINGS_MODEL_NAME=sentence-transformers/all-mpnet-base-v2
        - TARGET_SOURCE_CHUNKS=5
      command: ["python", "-m", "uvicorn", "api_endpoints:app", "--host", "0.0.0.0", "--port", "8081"]
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

volumes:
  index_data:

networks:
  net:
